package Interfaz;

import FUNCIONES.Conexion;
import javax.swing.ImageIcon;



/**
 * @author Sara
 */
public class MongoJframe extends javax.swing.JFrame {

    /**
     * Creates new form MongoJframe
     */Conexion con = new Conexion();
    public MongoJframe() {
       
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../FUNCIONES/movie-icon-11.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaConsulta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuConsultas = new javax.swing.JMenu();
        MenuTitulo = new javax.swing.JMenuItem();
        MenuFranquicia = new javax.swing.JMenuItem();
        MenuRango = new javax.swing.JMenuItem();
        mnuProductora = new javax.swing.JMenu();
        mnuBasicaProductora = new javax.swing.JMenuItem();
        mnuProductoraCompleta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONSULTAR PELICULAS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Informacion de Películas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 420, 60));

        jScrollPane1.setBackground(new java.awt.Color(153, 255, 255));

        AreaConsulta.setColumns(20);
        AreaConsulta.setRows(5);
        AreaConsulta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                AreaConsultaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(AreaConsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 510, 310));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sara\\Desktop\\maxresdefault.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 980, 530));

        MenuConsultas.setText("Consultar por:");

        MenuTitulo.setText("Título");
        MenuTitulo.setHideActionText(true);
        MenuTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTituloActionPerformed(evt);
            }
        });
        MenuConsultas.add(MenuTitulo);

        MenuFranquicia.setText("Franquicia");
        MenuFranquicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFranquiciaActionPerformed(evt);
            }
        });
        MenuConsultas.add(MenuFranquicia);

        MenuRango.setText("Rango años");
        MenuRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRangoActionPerformed(evt);
            }
        });
        MenuConsultas.add(MenuRango);

        mnuProductora.setText("Productora");

        mnuBasicaProductora.setText("Info Basica");
        mnuBasicaProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBasicaProductoraActionPerformed(evt);
            }
        });
        mnuProductora.add(mnuBasicaProductora);

        mnuProductoraCompleta.setText("Info Completa");
        mnuProductoraCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductoraCompletaActionPerformed(evt);
            }
        });
        mnuProductora.add(mnuProductoraCompleta);

        MenuConsultas.add(mnuProductora);

        jMenuBar1.add(MenuConsultas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuFranquiciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFranquiciaActionPerformed
        // TODO add your handling code here:
        JFranquicia F1= new JFranquicia();
        F1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuFranquiciaActionPerformed

    private void MenuTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTituloActionPerformed
        // TODO add your handling code here:
        JTitulo T1= new JTitulo();
        
        T1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_MenuTituloActionPerformed

    private void MenuRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRangoActionPerformed
        // TODO add your handling code here:
        JRango R1= new JRango();
        R1.setVisible(true);
    }//GEN-LAST:event_MenuRangoActionPerformed

    private void AreaConsultaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_AreaConsultaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaConsultaAncestorAdded

    private void mnuProductoraCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductoraCompletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuProductoraCompletaActionPerformed

    private void mnuBasicaProductoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBasicaProductoraActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JProductora1 P1 = new JProductora1();
        P1.setVisible(true);
    }//GEN-LAST:event_mnuBasicaProductoraActionPerformed
    public void AgrearATextArea(String Titulo) throws Exception{
       // Conexion c= new Conexion();
       
       con.ConectarBase();
        con.MostrarPeliculasTitulo(AreaConsulta, Titulo);
    }
    
     public void AgregarPorFranquicia(String Franquicia)throws Exception{
        con.ConectarBase();
        con.MostrarPeliculasFranquicia(AreaConsulta, Franquicia);
    }
     
    public void AgregarPorRango(int R1, int R2) throws Exception{
        
        con.ConectarBase();
        con.AgregarPorRango(AreaConsulta, R1, R2);
        
    }    
    
    public void AgregarPorPoductora1(String Productora) throws Exception{
        con.ConectarBase();
        con.FuncionProductora1(AreaConsulta, Productora);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MongoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MongoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MongoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MongoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MongoJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaConsulta;
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenuItem MenuFranquicia;
    private javax.swing.JMenuItem MenuRango;
    private javax.swing.JMenuItem MenuTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuBasicaProductora;
    private javax.swing.JMenu mnuProductora;
    private javax.swing.JMenuItem mnuProductoraCompleta;
    // End of variables declaration//GEN-END:variables
}
